### ISSUE TITLE
A removed subordinate causes a traceback in `terraform plan`

### ISSUE THREAD

**Issue by mthaddon** [juju/terraform-provider-juju#187]
This is similar to https://github.com/juju/terraform-provider-juju/issues/186 but with the difference that if you remove the subordinate application (not just the relation to the subordinate application) `terraform plan` tracebacks.

### Terraform version
```
$ terraform -v
Terraform v1.4.3-dev
on linux_amd64
+ provider registry.terraform.io/juju/juju v0.6.0

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
juju_integration

### Terraform Configuration Files
```
locals {
  charm_name    = "ubuntu"
  charm_channel = "latest/stable"
}

terraform {
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "0.6.0"
    }
  }
}
provider "juju" {}

resource "juju_model" "relation_test" {
  name = "relation-test"
}

resource "juju_application" "ubuntu" {
  name  = "ubuntu"
  model = juju_model.relation_test.name

  charm {
    name    = local.charm_name
    channel = local.charm_channel
  }

  config = {}

  units = 1
}


resource "juju_application" "telegraf" {
  name = "telegraf"
  model = juju_model.relation_test.name

  charm {
    name = "telegraf"
  }

  units = 0
}

resource "juju_integration" "ubuntu_telegraf" {
  model = juju_model.relation_test.name

  application {
    name = "ubuntu"
  }

  application {
    name = "telegraf"
  }  
}
```
### Debug Output
```
mthaddon@finistere:~/Documents/tmp/tf-relations$ terraform plan
juju_model.relation_test: Refreshing state... [id=d5aa68d0-db27-4156-8ae8-8c814c1e721c]
juju_integration.ubuntu_telegraf: Refreshing state... [id=relation-test:ubuntu:juju-info:telegraf:juju-info]
juju_application.telegraf: Refreshing state... [id=relation-test:telegraf]
juju_application.ubuntu: Refreshing state... [id=relation-test:ubuntu]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│ 
│   with juju_application.ubuntu,
│   on main.tf line 20, in resource "juju_application" "ubuntu":
│   20: resource "juju_application" "ubuntu" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with juju_application.telegraf,
│   on main.tf line 35, in resource "juju_application" "telegraf":
│   35: resource "juju_application" "telegraf" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with juju_integration.ubuntu_telegraf,
│   on main.tf line 46, in resource "juju_integration" "ubuntu_telegraf":
│   46: resource "juju_integration" "ubuntu_telegraf" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-juju_v0.6.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x1c77b33]

goroutine 41 [running]:
github.com/juju/terraform-provider-juju/internal/juju.applicationsClient.ReadApplication({{{{0xc000758450, 0x1, 0x1}, {0xc00022b219, 0x5}, {0xc00005e580, 0x20}, {0xc000063800, 0x5c0}}}}, 0xc0005cf158)
        github.com/juju/terraform-provider-juju/internal/juju/applications.go:520 +0x393
github.com/juju/terraform-provider-juju/internal/provider.resourceApplicationRead({0x2673500?, 0xc000901680?}, 0xc000424880, {0x1d8e8a0?, 0xc00074a900})
        github.com/juju/terraform-provider-juju/internal/provider/resource_application.go:243 +0x354
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00023a9a0, {0x2673500, 0xc000901680}, 0xd?, {0x1d8e8a0, 0xc00074a900})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00023a9a0, {0x2673500, 0xc000901680}, 0xc000747ad0, {0x1d8e8a0, 0xc00074a900})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0008163d8, {0x2673500?, 0xc000901560?}, 0xc000792f80)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00043e0a0, {0x2673500?, 0xc000900db0?}, 0xc00039f320)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x214cb40?, 0xc00043e0a0}, {0x2673500, 0xc000900db0}, 0xc0004f2540, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003d23c0, {0x267bcc0, 0xc000382d00}, 0xc00092c120, 0xc000317a10, 0x36c0450, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0003d23c0, {0x267bcc0, 0xc000382d00}, 0xc00092c120, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-juju_v0.6.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Expected Behavior
I would expect terraform plan to simply say it's going to re-install the charm and re-establish the relation.

### Actual Behavior

See above

**Comment by juanmanuel-tirado** [comment]
This problem looks fixed by #192
