### ISSUE TITLE
stack trace running `terraform apply`

### ISSUE THREAD

**Issue by mthaddon** [juju/terraform-provider-juju#399]
### Description

I got a stack trace running `terraform apply`. Rerunning it ran without error.

### Urgency

Casually reporting

### Terraform Juju Provider version

0.10.1

### Terraform version

v1.7.2-dev

### Terraform Configuration(s)

```terraform
This was related to adding some subordinate charms to a machine model.
```

### Reproduce / Test

```shell
I'm not able to reproduce
```

### Debug/Panic Output

```shell
prod-github-runner-snapcraft@is-bastion-ps6:~/plan$ terraform apply
module.subordinates.data.vault_generic_secret.ubuntu_pro_token: Reading...
module.subordinates.data.vault_generic_secret.landscape_registration_key: Reading...
juju_model.github_runners_snapcraft: Refreshing state... [id=350e17a5-5487-467d-82b2-486f70c56189]
module.subordinates.data.vault_generic_secret.landscape_registration_key: Read complete after 0s [id=secret/juju/common/subordinates/landscape-registration]
module.subordinates.data.vault_generic_secret.ubuntu_pro_token: Read complete after 0s [id=secret/juju/common/subordinates/ubuntu-pro]
╷
│ Warning: Attribute Deprecated
│
│   with juju_application.github_runner_large,
│   on main.tf line 76, in resource "juju_application" "github_runner_large":
│   76:     series   = local.charm_series
│
│ Configure base instead. This attribute will be removed in the next major version of the provider.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-juju_v0.10.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d1ff7f]

goroutine 59 [running]:
github.com/juju/terraform-provider-juju/internal/juju.(*modelsClient).ReadModel(0xc0006e8490, {0xc00084a020, 0x1c})
        github.com/juju/terraform-provider-juju/internal/juju/models.go:235 +0x41f
github.com/juju/terraform-provider-juju/internal/provider.(*modelResource).Read(0xc000636b88, {0x27478a0, 0xc00083eae0}, {{{{0x2750930, 0xc00084d860}, {0x1fd1020, 0xc00084d4a0}}, {0x2755c60, 0xc00036a6e0}}, 0xc00032c4f0, ...}, ...)
        github.com/juju/terraform-provider-juju/internal/provider/resource_model.go:286 +0x2ef
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc000608000, {0x27478a0, 0xc00083eae0}, 0xc00083eb70, 0xc000787648)
        github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/fwserver/server_readresource.go:101 +0x677
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc000608000, {0x27478a0?, 0xc00083e990?}, 0xc000218e00)
        github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/proto6server/server_readresource.go:55 +0x41a
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc00033c140, {0x27478a0?, 0xc00083e000?}, 0xc000629500)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:749 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x2239ac0?, 0xc00033c140}, {0x27478a0, 0xc00083e000}, 0xc0002c0d20, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:386 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c8000, {0x27516a0, 0xc000502ea0}, 0xc000640fc0, 0xc000121a10, 0x3865a70, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0001c8000, {0x27516a0, 0xc000502ea0}, 0xc000640fc0, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.1/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.1/server.go:957 +0x18c

Error: The terraform-provider-juju_v0.10.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

prod-github-runner-snapcraft@is-bastion-ps6:~/plan$
prod-github-runner-snapcraft@is-bastion-ps6:~/plan$ juju status
Model                         Controller    Cloud/Region           Version  SLA          Timestamp
prod-github-runner-snapcraft  prodstack-is  prodstack6/prodstack6  3.1.6    unsupported  09:44:25Z

App               Version  Status   Scale  Charm             Channel        Rev  Exposed  Message
landscape-client           unknown      0  landscape-client  stable          49  no
large                      active       4  github-runner     latest/stable  114  no
telegraf                   unknown      0  telegraf          stable          68  yes
ubuntu-advantage           unknown      0  ubuntu-advantage  stable          43  no

Unit       Workload  Agent  Machine  Public address  Ports  Message
large/12*  active    idle   12       10.145.244.243
large/13   active    idle   13       10.145.244.73
large/14   active    idle   14       10.145.244.71
large/15   active    idle   15       10.145.244.132

Machine  State    Address         Inst id                               Base          AZ                   Message
12       started  10.145.244.243  8e1c1d5f-5420-4811-b536-58c6766bc072  ubuntu@22.04  availability-zone-3  ACTIVE
13       started  10.145.244.73   e48ab55f-ada0-4600-a3b8-d64ddc1a6c85  ubuntu@22.04  availability-zone-2  ACTIVE
14       started  10.145.244.71   a9ab2133-5b0a-4748-9349-744779d05d4a  ubuntu@22.04  availability-zone-1  ACTIVE
15       started  10.145.244.132  25f110ca-bb11-48a4-b9af-48e6836503d6  ubuntu@22.04  availability-zone-1  ACTIVE
prod-github-runner-snapcraft@is-bastion-ps6:~/plan$
prod-github-runner-snapcraft@is-bastion-ps6:~/plan$
prod-github-runner-snapcraft@is-bastion-ps6:~/plan$ terraform apply
module.subordinates.data.vault_generic_secret.landscape_registration_key: Reading...
module.subordinates.data.vault_generic_secret.ubuntu_pro_token: Reading...
juju_model.github_runners_snapcraft: Refreshing state... [id=350e17a5-5487-467d-82b2-486f70c56189]
module.subordinates.data.vault_generic_secret.landscape_registration_key: Read complete after 1s [id=secret/juju/common/subordinates/landscape-registration]
module.subordinates.data.vault_generic_secret.ubuntu_pro_token: Read complete after 1s [id=secret/juju/common/subordinates/ubuntu-pro]
juju_application.github_runner_large: Refreshing state... [id=prod-github-runner-snapcraft:large]
module.subordinates.juju_application.ubuntu_pro[0]: Refreshing state... [id=prod-github-runner-snapcraft:ubuntu-advantage]
module.subordinates.juju_application.landscape-client[0]: Refreshing state... [id=prod-github-runner-snapcraft:landscape-client]
module.subordinates.juju_application.telegraf[0]: Refreshing state... [id=prod-github-runner-snapcraft:telegraf]
module.subordinates.juju_integration.telegraf["large"]: Refreshing state... [id=prod-github-runner-snapcraft:large:juju-info:telegraf:juju-info]
module.subordinates.juju_integration.ubuntu_pro["large"]: Refreshing state... [id=prod-github-runner-snapcraft:large:juju-info:ubuntu-advantage:juju-info]
module.subordinates.juju_integration.landscape_client["large"]: Refreshing state... [id=prod-github-runner-snapcraft:large:juju-info:landscape-client:container]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.subordinates.juju_integration.landscape_client["large"] will be created
  + resource "juju_integration" "landscape_client" {
      + id    = (known after apply)
      + model = "prod-github-runner-snapcraft"

      + application {
          + endpoint = "container"
          + name     = "landscape-client"
        }
      + application {
          + endpoint = "juju-info"
          + name     = "large"
        }
    }

  # module.subordinates.juju_integration.telegraf["large"] will be created
  + resource "juju_integration" "telegraf" {
      + id    = (known after apply)
      + model = "prod-github-runner-snapcraft"

      + application {
          + endpoint = "juju-info"
          + name     = "large"
        }
      + application {
          + endpoint = "juju-info"
          + name     = "telegraf"
        }
    }

  # module.subordinates.juju_integration.ubuntu_pro["large"] will be created
  + resource "juju_integration" "ubuntu_pro" {
      + id    = (known after apply)
      + model = "prod-github-runner-snapcraft"

      + application {
          + endpoint = "juju-info"
          + name     = "large"
        }
      + application {
          + endpoint = "juju-info"
          + name     = "ubuntu-advantage"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.
╷
│ Warning: Attribute Deprecated
│
│   with juju_application.github_runner_large,
│   on main.tf line 76, in resource "juju_application" "github_runner_large":
│   76:     series   = local.charm_series
│
│ Configure base instead. This attribute will be removed in the next major version of the provider.
│
│ (and 4 more similar warnings elsewhere)
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.subordinates.juju_integration.telegraf["large"]: Creating...
module.subordinates.juju_integration.landscape_client["large"]: Creating...
module.subordinates.juju_integration.ubuntu_pro["large"]: Creating...
module.subordinates.juju_integration.landscape_client["large"]: Creation complete after 5s [id=prod-github-runner-snapcraft:large:juju-info:landscape-client:container]
module.subordinates.juju_integration.telegraf["large"]: Creation complete after 5s [id=prod-github-runner-snapcraft:large:juju-info:telegraf:juju-info]
module.subordinates.juju_integration.ubuntu_pro["large"]: Creation complete after 5s [id=prod-github-runner-snapcraft:large:juju-info:ubuntu-advantage:juju-info]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

**Comment by anvial** [comment]
@mthaddon, 

can I ask for the plan? I wish to catch it locally.

**Comment by hmlanigan** [comment]
@anvial looking at the stack trace, it looks like we got caught by an intermittent juju bug:

https://github.com/juju/terraform-provider-juju/blob/6b709e03ab946d740276a85e67a612902d0ec71b/internal/juju/models.go#L223-L235

We can be more defensive here to avoid a panic.
