### ISSUE TITLE
Segmentation violation on terraform apply

### ISSUE THREAD

**Issue by andersson1234** [juju/terraform-provider-juju#549]
### Description

I was using terraform apply earlier in the day with absolutely no issue, and all of a sudden I started getting a segmentation violation

### Urgency

Casually reporting

### Terraform Juju Provider version

0.13.0

### Terraform version

v1.9.4-dev

### Juju version

No access to this (I think 2.9.49)

### Terraform Configuration(s)

```terraform
terraform {
  required_version = ">= 1.0"
  required_providers {
    juju = {
      version = "0.13.0"
      source  = "juju/juju"
    }
  }
}

#####################################################
#####################################################
# Provider declaration
provider "juju" {}

#####################################################
#####################################################
# Local variable declarations
locals {
    # unused... FOR NOW!!!
    # http_proxy = "http://squid.internal:3128"
    hostname = "autopkgtest.staging.ubuntu.com"
    https_proxy = "http://squid.internal:3128"
    no_proxy = "127.0.0.1,127.0.1.1,login.ubuntu.com,localhost,localdomain,novalocal,internal,archive.ubuntu.com,ports.ubuntu.com,security.ubuntu.com,ddebs.ubuntu.com,changelogs.ubuntu.com,keyserver.ubuntu.com,launchpadlibrarian.net,launchpadcontent.net,launchpad.net,10.24.0.0/24,keystone.ps5.canonical.com,objectstorage.prodstack5.canonical.com"
    storage_host_internal = "objectstorage.prodstack5.canonical.com:443"
    storage_path_internal = "/swift/v1/AUTH_cc509e38c54f4edebda2fd17557309bb"
    # series = "focal"
    stage_name = "staging"
    base = "ubuntu@20.04"
    releases = "focal jammy mantic noble"
    channel = "latest/edge"
    local_dir = "/home/stg-proposed-migration-environment/.local/share/mojo/LOCAL/autopkgtest-cloud"
    model_name = "stg-proposed-migration-environment"
}

#####################################################
#####################################################
# Machine declarations
resource "juju_machine" "cloud_worker_machine" {
  model = local.model_name
  base = local.base
  name = "cloud_worker_machine"
}

resource "juju_machine" "apache2_machine" {
  model = local.model_name
  base = local.base
  name = "apache2_machine"
}

#####################################################
#####################################################
# Application declarations

#####################################################
# Miscellanious applications
resource "juju_application" "telegraf" {
  name = "telegraf"
  model = local.model_name
    charm {
    name = "telegraf"
    channel = "latest/stable"
  }
  units = 0
  expose {
    cidrs = "0.0.0.0/0,::/0"
  }

  config = {
    install_method = "snap"
  }
}

#******************************************************************
# NOT WORKING!
#******************************************************************
resource "juju_application" "landscape_client" {
  name = "landscape-client"
  model = local.model_name
  charm {
    name = "landscape-client"
    channel = "latest/stable"
  }
  units = 0
}

#******************************************************************
# NOT WORKING!
#******************************************************************
resource "juju_application" "ubuntu_advantage" {
    name = "ubuntu-advantage"
    model = local.model_name
    charm {
        name = "ubuntu-advantage"
        channel = "latest/stable"
    }
    units = 0
}

#####################################################
# cloud worker applications
resource "juju_application" "autopkgtest_cloud_worker" {
  name = "autopkgtest-cloud-worker"
  model = local.model_name

  charm {
    name = "ubuntu-release-autopkgtest-cloud-worker"
    channel = local.channel
    # series = local.series
    base = local.base
  }
  placement = juju_machine.cloud_worker_machine.machine_id

  # this works but doesn't match the documentation...
  storage_directives = {
    tmp = "200G"
  }

  units = 1
  # We should add a hacky script or workaround to mount the /tmp ceph storage
  constraints = "arch=amd64 cores=8 mem=16384M root-disk=40960M"

  config = {
    swift-password = file("${local.local_dir}/${local.stage_name}/swift_password")
    releases = local.releases
    influxdb-hostname = file("${local.local_dir}/${local.stage_name}/influx-hostname.txt")
    influxdb-password = file("${local.local_dir}/${local.stage_name}/influx-password.txt")
    influxdb-database = "metrics"
    # big if block here kinda
    influxdb-username = "stg_proposed_migration"
    influxdb-context = local.stage_name
    swift-username = "stg-proposed-migration-environment"
    swift-region = "prodstack5"
    swift-auth-url = "https://keystone.ps5.canonical.com:5000/v3"
    swift-tenant = "stg-proposed-migration-environment_project"
    swift-auth-version = "3"
    swift-project-domain-name = "Default"
    swift-project-name = "stg-proposed-migration-environment_project"
    swift-user-domain-name = "Default"
    # More common options
    # Need to figure out how to do this one!
    # nova-rcs: include-base64://{{local_dir}}/novarcs.tar
    worker-tmp-cleanup-config = "D /tmp 1777 root root 30d"
    worker-upstream-percentage = 33
    worker-net-names = <<-EOT
        default: net_stg-proposed-migration
        bos03:
          ppc64el: net_stg-proposed-migration-ppc64el
          s390x: net_stg-proposed-migration-s390x
        EOT
    worker-flavor-config = <<-EOT
        default: stag-cpu2-ram4-disk20
        big: stag-cpu4-ram16-disk50
        bos03:
          ppc64el:
            default: builder-ppc64el-cpu2-ram4-disk20
            big: builder-ppc64el-cpu2-ram4-disk100
          s390x:
            default: autopkgtest-s390x
            big: autopkgtest-big-s390x
        EOT
    mirror = "http://ftpmaster.internal/ubuntu"
    worker-args = "ssh -s /CHECKOUTDIR//ssh-setup/nova -- --flavor $PACKAGESIZE --security-groups $SECGROUP --name adt-$RELEASE-$ARCHITECTURE-$PACKAGENAME-$TIMESTAMP-$HOSTNAME-$UUID --image adt/ubuntu-$RELEASE-$HOSTARCH-server --keyname testbed-/HOSTNAME/ --net-id=/NET_NAME/ -e TERM=linux -e 'http_proxy={{ http_proxy }}' -e 'https_proxy={{ https_proxy }}' -e 'no_proxy={{ no_proxy }}' --mirror=/MIRROR/"
    worker-setup-command = "/home/ubuntu/autopkgtest-cloud/worker-config/production/setup-canonical.sh"
    n-workers = <<-EOT
        lcy02:
            amd64: 1
        bos01:
            arm64: 1
            ppc64el: 1
            s390x: 1
        bos02:
            arm64: 1
            ppc64el: 1
            s390x: 1
        EOT
  }
}

#####################################################
# web applications
resource "juju_application" "apache2" {
  name = "apache2"
  model = local.model_name
  trust = true
  charm {
    name = "apache2"
    channel = "latest/stable"
    revision = 41
    base = local.base
  }
  placement = juju_machine.apache2_machine.machine_id
  units = 1
  config = {
    enable_modules = "include cgi proxy proxy_http"
    mpm_type = "prefork"
  }
}

resource "juju_application" "autopkgtest_web" {
  name = "autopkgtest-web"

  model = local.model_name

    charm {
    name     = "ubuntu-release-autopkgtest-web"
    channel  = local.channel
    base = local.base
  }
  units = 0

  config = {
    hostname = local.hostname
    allowed-requestor-teams = <<-EOT
        autopkgtest-requestors
        canonical-foundations
        canonical-kernel-distro-team
        canonical-partner-eng
        canonical-security
        canonical-server
        canonical-ubuntu-qa
        EOT
    storage-url-internal = "https://${local.storage_host_internal}${local.storage_path_internal}"
    github-secrets = file("${local.local_dir}/${local.stage_name}/github-secrets.json")
    github-status-credentials = file("${local.local_dir}/${local.stage_name}/github-status-credentials.txt")
    swift-web-credentials = file("${local.local_dir}/${local.stage_name}/swift-web-credentials.conf")
    public-swift-creds = file("${local.local_dir}/${local.stage_name}/public-swift-creds")
    external-web-requests-api-keys = file("${local.local_dir}/${local.stage_name}/external-web-requests-api-keys.json")
    https-proxy = local.https_proxy
    no-proxy = local.no_proxy
    cookies = "S0 S1"
    indexed-packages-fp = "/home/ubuntu/indexed-packages.json"
  }
}


#####################################################
#####################################################
# Integration declarations
resource "juju_integration" "autopkgtest_cloud_worker-telegraf" {
  model = local.model_name
  application {
    name = juju_application.autopkgtest_cloud_worker.name
    endpoint = "juju-info"
  }
  application {
    name = juju_application.telegraf.name
    endpoint = "juju-info"
  }
  lifecycle {
    replace_triggered_by = [
      juju_application.autopkgtest_cloud_worker.name,
      juju_application.autopkgtest_cloud_worker.model,
      juju_application.autopkgtest_cloud_worker.constraints,
      juju_application.autopkgtest_cloud_worker.placement,
      juju_application.autopkgtest_cloud_worker.charm.name,
      juju_application.telegraf.name,
      juju_application.telegraf.model,
      juju_application.telegraf.constraints,
      juju_application.telegraf.placement,
      juju_application.telegraf.charm.name,
    ]
  }
}

#******************************************************************
# NOT WORKING!
#******************************************************************
# resource "juju_integration" "autopkgtest_cloud_worker-landscape_client" {
#   model = local.model_name
#   application {
#     name = juju_application.autopkgtest_cloud_worker.name
#     endpoint = "juju-info"
#   }
#   application {
#     name = juju_application.landscape_client.name
#     endpoint = "juju-info"
#   }
#   lifecycle {
#     replace_triggered_by = [
#       juju_application.autopkgtest_cloud_worker.name,
#       juju_application.autopkgtest_cloud_worker.model,
#       juju_application.autopkgtest_cloud_worker.constraints,
#       juju_application.autopkgtest_cloud_worker.placement,
#       juju_application.autopkgtest_cloud_worker.charm.name,
#       juju_application.landscape_client.name,
#       juju_application.landscape_client.model,
#       juju_application.landscape_client.constraints,
#       juju_application.landscape_client.placement,
#       juju_application.landscape_client.charm.name,
#     ]
#   }
# }

#******************************************************************
# NOT WORKING!
#******************************************************************
# resource "juju_integration" "autopkgtest_cloud_worker-ubuntu_advantage" {
#   model = local.model_name
#   application {
#     name = juju_application.autopkgtest_cloud_worker.name
#     endpoint = "juju-info"
#   }
#   application {
#     name = juju_application.ubuntu_advantage.name
#     endpoint = "juju-info"
#   }
#   lifecycle {
#     replace_triggered_by = [
#       juju_application.autopkgtest_cloud_worker.name,
#       juju_application.autopkgtest_cloud_worker.model,
#       juju_application.autopkgtest_cloud_worker.constraints,
#       juju_application.autopkgtest_cloud_worker.placement,
#       juju_application.autopkgtest_cloud_worker.charm.name,
#       juju_application.ubuntu_advantage.name,
#       juju_application.ubuntu_advantage.model,
#       juju_application.ubuntu_advantage.constraints,
#       juju_application.ubuntu_advantage.placement,
#       juju_application.ubuntu_advantage.charm.name,
#     ]
#   }
# }

resource "juju_integration" "apache2-autopkgtest-web" {
  model = local.model_name
  application {
    name = juju_application.apache2.name
    endpoint = "apache-website"
  }
  application {
    name = juju_application.autopkgtest_web.name
    endpoint = "website"
  }
  lifecycle {
    replace_triggered_by = [
      juju_application.apache2.name,
      juju_application.apache2.model,
      juju_application.apache2.constraints,
      juju_application.apache2.placement,
      juju_application.apache2.charm.name,
      juju_application.autopkgtest_web.name,
      juju_application.autopkgtest_web.model,
      juju_application.autopkgtest_web.constraints,
      juju_application.autopkgtest_web.placement,
      juju_application.autopkgtest_web.charm.name,
    ]
  }
}

resource "juju_integration" "apache2-telegraf" {
  model = local.model_name
  application {
    name = juju_application.apache2.name
    endpoint = "juju-info"
  }
  application {
    name = juju_application.telegraf.name
    endpoint = "juju-info"
  }
  lifecycle {
    replace_triggered_by = [
      juju_application.apache2.name,
      juju_application.apache2.model,
      juju_application.apache2.constraints,
      juju_application.apache2.placement,
      juju_application.apache2.charm.name,
      juju_application.telegraf.name,
      juju_application.telegraf.model,
      juju_application.telegraf.constraints,
      juju_application.telegraf.placement,
      juju_application.telegraf.charm.name,
    ]
  }
}

#******************************************************************
# NOT WORKING!
#******************************************************************
# resource "juju_integration" "apache2-landscape_client" {
#   model = local.model_name
#   application {
#     name = juju_application.apache2.name
#     endpoint = "juju-info"
#   }
#   application {
#     name = juju_application.landscape_client.name
#     endpoint = "container"
#   }
#   lifecycle {
#     replace_triggered_by = [
#       juju_application.apache2.name,
#       juju_application.apache2.model,
#       juju_application.apache2.constraints,
#       juju_application.apache2.placement,
#       juju_application.apache2.charm.name,
#       juju_application.landscape_client.name,
#       juju_application.landscape_client.model,
#       juju_application.landscape_client.constraints,
#       juju_application.landscape_client.placement,
#       juju_application.landscape_client.charm.name,
#     ]
#   }
# }

# resource "juju_integration" "apache2-ubuntu_advantage" {
#   model = local.model_name
#   application {
#     name = juju_application.apache2.name
#     endpoint = "juju-info"
#   }
#   application {
#     name = juju_application.ubuntu_advantage.name
#     endpoint = "juju-info"
#   }
#   lifecycle {
#     replace_triggered_by = [
#       juju_application.apache2.name,
#       juju_application.apache2.model,
#       juju_application.apache2.constraints,
#       juju_application.apache2.placement,
#       juju_application.apache2.charm.name,
#       juju_application.ubuntu_advantage.name,
#       juju_application.ubuntu_advantage.model,
#       juju_application.ubuntu_advantage.constraints,
#       juju_application.ubuntu_advantage.placement,
#       juju_application.ubuntu_advantage.charm.name,
#     ]
#   }
# }
```

### Reproduce / Test

```shell
terraform init
terraform apply

# You may need to do this in the environment to reproduce - happy to hop on a call to debug
```

### Debug/Panic Output

```shell
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

juju_machine.apache2_machine: Creating...
juju_machine.cloud_worker_machine: Creating...
juju_application.telegraf: Creating...
juju_application.ubuntu_advantage: Creating...
juju_application.landscape_client: Creating...
juju_application.autopkgtest_web: Creating...
juju_machine.cloud_worker_machine: Creation complete after 2s [id=stg-proposed-migration-environment:123:cloud_worker_machine]
juju_machine.apache2_machine: Creation complete after 3s [id=stg-proposed-migration-environment:124:apache2_machine]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-juju_v0.13.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e5a03b]

goroutine 59 [running]:
github.com/juju/terraform-provider-juju/internal/juju.transformToStorageConstraints({0xc000174b40, 0x2, 0x1?}, {0xc000684320, 0x1, 0x0?}, {0xc000004300, 0x4, 0xfc996b6115c1b6cf?})
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:856 +0x4bb
github.com/juju/terraform-provider-juju/internal/juju.applicationsClient.ReadApplication({{0x2982d70, 0xc0006b58c0}, {0x0, 0x0, {0x0, 0x0}, 0x0, 0x0}, 0x269b718, 0xc0006811a0, ...}, ...)
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:928 +0x4ca
github.com/juju/terraform-provider-juju/internal/juju.applicationsClient.ReadApplicationWithRetryOnNotFound.func1()
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:766 +0x78
github.com/juju/retry.Call({0xc000a28ab0, 0x269b738, 0xc0002d52d0, 0x1e, 0x3b9aca00, 0x0, 0x0, 0x269b708, {0x295a7e8, 0x3c210a0}, ...})
	github.com/juju/retry@v1.0.0/retry.go:183 +0xc3
github.com/juju/terraform-provider-juju/internal/juju.applicationsClient.ReadApplicationWithRetryOnNotFound({{0x2982d70, 0xc0006b58c0}, {0x0, 0x0, {0x0, 0x0}, 0x0, 0x0}, 0x269b718, 0xc0006811a0, ...}, ...)
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:763 +0x2d8
github.com/juju/terraform-provider-juju/internal/provider.(*applicationResource).Create(0xc000130cc0, {0x29765f0, 0xc000993080}, {{{{0x297e990, 0xc00085f1a0}, {0x2171cc0, 0xc0007db4d0}}, {0x2985688, 0xc0006935e0}}, {{{0x297e990, ...}, ...}, ...}, ...}, ...)
	github.com/juju/terraform-provider-juju/internal/provider/resource_application.go:570 +0x188b
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc000238d20, {0x29765f0, 0xc000993080}, 0xc00071d580, 0xc00071d520)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_createresource.go:101 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc000b3d6d8?, {0x29765f0, 0xc000993080}, 0xc0003a2280, 0xc00071d6d8)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_applyresourcechange.go:57 +0x4a5
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc000238d20, {0x29765f0?, 0xc000992ed0?}, 0xc0003a21e0)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/proto6server/server_applyresourcechange.go:55 +0x3e5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc000584140, {0x29765f0?, 0xc000992660?}, 0xc0002bcaf0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x249d7c0?, 0xc000584140}, {0x29765f0, 0xc000992660}, 0xc00020ca00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004bc000, {0x29765f0, 0xc0009925a0}, {0x29803b0, 0xc0001fe300}, 0xc0009d25a0, 0xc0006222d0, 0x3bc86f8, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0004bc000, {0x29803b0, 0xc0001fe300}, 0xc0009d25a0)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 22
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-juju_v0.13.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by hmlanigan** [comment]
I'm unable to reproduce the panic. Based on the stack trace, I can made an educated guess as to the cause.

**Comment by sed-i** [comment]
I just got this while running `terraform test` on https://github.com/canonical/mimir-worker-k8s-operator/pull/74.

```
Stack trace from the terraform-provider-juju_v0.13.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e59dbb]

goroutine 50 [running]:
github.com/juju/terraform-provider-juju/internal/juju.transformToStorageConstraints({0xc0008be800, 0xc, 0x1?}, {0xc0008c2a80, 0xe, 0x203c4c0?}, {0xc0008f8c00, 0xe, 0xc0005f7828?})
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:843 +0x23b
github.com/juju/terraform-provider-juju/internal/juju.applicationsClient.ReadApplication({{0x2982d70, 0xc00039cd80}, {0x0, 0x0, {0x0, 0x0}, 0x0, 0x0}, 0x269b718, 0xc0002ff140, ...}, ...)
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:928 +0x4ca
github.com/juju/terraform-provider-juju/internal/juju.applicationsClient.ReadApplicationWithRetryOnNotFound.func1()
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:766 +0x78
github.com/juju/retry.Call({0xc0007a8fc0, 0x269b738, 0xc0002d58f0, 0x1e, 0x1dcd65000, 0x0, 0x0, 0x269b708, {0x295a7e8, 0x3c210a0}, ...})
	github.com/juju/retry@v1.0.0/retry.go:183 +0xc3
github.com/juju/terraform-provider-juju/internal/juju.applicationsClient.ReadApplicationWithRetryOnNotFound({{0x2982d70, 0xc00039cd80}, {0x0, 0x0, {0x0, 0x0}, 0x0, 0x0}, 0x269b718, 0xc0002ff140, ...}, ...)
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:763 +0x2d8
github.com/juju/terraform-provider-juju/internal/provider.(*applicationResource).Create(0xc00090c8d0, {0x29765f0, 0xc0003dc660}, {{{{0x297e990, 0xc000846ea0}, {0x2171cc0, 0xc000840a80}}, {0x2985688, 0xc000447450}}, {{{0x297e990, ...}, ...}, ...}, ...}, ...)
	github.com/juju/terraform-provider-juju/internal/provider/resource_application.go:570 +0x188b
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0002463c0, {0x29765f0, 0xc0003dc660}, 0xc0005f9580, 0xc0005f9520)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_createresource.go:101 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc0005336d8?, {0x29765f0, 0xc0003dc660}, 0xc00090e870, 0xc0005f96d8)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_applyresourcechange.go:57 +0x4a5
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc0002463c0, {0x29765f0?, 0xc0002b7890?}, 0xc00090e7d0)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/proto6server/server_applyresourcechange.go:55 +0x3e5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc00045a320, {0x29765f0?, 0xc0006895c0?}, 0xc0002d62a0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x249d7c0?, 0xc00045a320}, {0x29765f0, 0xc0006895c0}, 0xc000218980, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000217000, {0x29765f0, 0xc000688a20}, {0x29803b0, 0xc000544000}, 0xc0002ca7e0, 0xc00068e3f0, 0x3bc86f8, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc000217000, {0x29803b0, 0xc000544000}, 0xc0002ca7e0)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 84
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-juju_v0.13.0 plugin crashed!
```

**Comment by hmlanigan** [comment]
@sed-i do you have a smaller reproducer? Is this reproducible?
