### ISSUE TITLE
storage_directives doesn't seem to work with juju version 2.9.49

### ISSUE THREAD

**Issue by andersson1234** [juju/terraform-provider-juju#617]
### Description

I don't have any better information than what I've put in the title, basically. I've been trying to deploy separate /tmp storage with a different tf file, but I've tried now just using the ubuntu charm, with a similar config to another project I'm aware of, where it works. In this other environment I mentioned, we're using juju version 3.5.3. In the environment I'm trying to deploy in, we're using juju version 2.9.49.

### Urgency

Casually reporting

### Terraform Juju Provider version

0.13.0

### Terraform version

v1.9.8-dev

### Juju version

2.9.49

### Terraform Configuration(s)

```terraform
terraform {
  required_version = ">= 1.0"
  required_providers {
    juju = {
      version = "0.13.0"
      source  = "juju/juju"
    }
  }
}

provider "juju" {}

locals {
  model_name = "stg-proposed-migration-environment"
}

resource "juju_application" "ubuntu" {
  name  = "ubuntu"
  model = local.model_name

  constraints = "arch=amd64 cores=8 mem=32768M root-disk=204800M"

  charm {
    name     = "ubuntu"
    revision = 24
    channel  = "latest/stable"
    base     = "ubuntu@22.04"
  }

  storage_directives = {
    block = "150G"
  }

  units = 1
}
```

### Reproduce / Test

```shell
terraform init && terraform apply
```

### Debug/Panic Output

```shell
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin
│ logs may contain more details.
╵

Stack trace from the terraform-provider-juju_v0.13.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e5a03b]

goroutine 52 [running]:
github.com/juju/terraform-provider-juju/internal/juju.transformToStorageConstraints({0xc0009362d0, 0x2, 0x1?}, {0x0, 0x0, 0x0?}, {0xc0006da900, 0x4, 0xb55a366279e84735?})
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:856 +0x4bb
github.com/juju/terraform-provider-juju/internal/juju.applicationsClient.ReadApplication({{0x2982d70, 0xc0003219e0}, {0x0, 0x0, {0x0, 0x0}, 0x0, 0x0}, 0x269b718, 0xc000649ed8, ...}, ...)
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:928 +0x4ca
github.com/juju/terraform-provider-juju/internal/juju.applicationsClient.ReadApplicationWithRetryOnNotFound.func1()
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:766 +0x78
github.com/juju/retry.Call({0xc0006bb440, 0x269b738, 0xc0004a5f10, 0x1e, 0x3b9aca00, 0x0, 0x0, 0x269b708, {0x295a7e8, 0x3c210a0}, ...})
	github.com/juju/retry@v1.0.0/retry.go:183 +0xc3
github.com/juju/terraform-provider-juju/internal/juju.applicationsClient.ReadApplicationWithRetryOnNotFound({{0x2982d70, 0xc0003219e0}, {0x0, 0x0, {0x0, 0x0}, 0x0, 0x0}, 0x269b718, 0xc000649ed8, ...}, ...)
	github.com/juju/terraform-provider-juju/internal/juju/applications.go:763 +0x2d8
github.com/juju/terraform-provider-juju/internal/provider.(*applicationResource).Create(0xc00074a1e0, {0x29765f0, 0xc00078eb40}, {{{{0x297e990, 0xc0007bad50}, {0x2171cc0, 0xc0007a1860}}, {0x2985688, 0xc000355ae0}}, {{{0x297e990, ...}, ...}, ...}, ...}, ...)
	github.com/juju/terraform-provider-juju/internal/provider/resource_application.go:570 +0x188b
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0001b6d20, {0x29765f0, 0xc00078eb40}, 0xc00084b580, 0xc00084b520)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_createresource.go:101 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc0007236d8?, {0x29765f0, 0xc00078eb40}, 0xc0005b0ff0, 0xc00084b6d8)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_applyresourcechange.go:57 +0x4a5
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc0001b6d20, {0x29765f0?, 0xc00078ea20?}, 0xc0005b0f50)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/proto6server/server_applyresourcechange.go:55 +0x3e5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0002fd720, {0x29765f0?, 0xc000357260?}, 0xc00022c0e0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x249d7c0?, 0xc0002fd720}, {0x29765f0, 0xc000357260}, 0xc000267280, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004f8000, {0x29765f0, 0xc000357140}, {0x29803b0, 0xc0004e4000}, 0xc0007925a0, 0xc000650270, 0x3bc86f8, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0004f8000, {0x29803b0, 0xc0004e4000}, 0xc0007925a0)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 21
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-juju_v0.13.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by hmlanigan** [comment]
duplicate of #549
